apiVersion: v1
kind: ServiceAccount
metadata:
  name: nutriai-service-account
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/part-of: nutriai
  annotations:
    azure.workload.identity/client-id: {{ .Values.clientID | quote }}
