apiVersion: v1
kind: ServiceAccount
metadata:
  name: nutriai-service-account
  namespace: {{ .Values.namespace | quote }}
  labels:
    app.kubernetes.io/part-of: nutriai
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: {{ .Values.clientID | quote }}
    azure.workload.identity/tenant-id: {{ .Values.tenantId | quote }}
    argocd.argoproj.io/sync-wave: "2"
