apiVersion: v1
kind: ServiceAccount
metadata:
  name: nutriai-service-account
  namespace: nutriai-prod
  labels:
    app.kubernetes.io/part-of: nutriai
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: "prod-identity-client-id"
