namespace: nutriai-dev
keyvaultName: nutriai-kv-dev
clientID: dev-identity-client-id
tenantId: placeholder-entra-tenant-id-dev

image:
  registry: nutriaiacr1602.azurecr.io
  pullPolicy: Always

ingress:
  host: dev.nutriai.example.com

admin-service:
  replicas: 1
  image:
    tag: latest

api-gateway:
  replicas: 2
  image:
    tag: latest

auth-service:
  replicas: 2
  image:
    tag: latest

diet-service:
  replicas: 2
  image:
    tag: latest
  hpa:
    minReplicas: 2
    maxReplicas: 3

document-service:
  replicas: 2
  image:
    tag: latest

frontend:
  replicas: 2
  image:
    tag: latest
  hpa:
    minReplicas: 2
    maxReplicas: 3

health-service:
  replicas: 2
  image:
    tag: latest

notification-service:
  replicas: 1
  image:
    tag: latest

profile-service:
  replicas: 2
  image:
    tag: latest

config:
  apiGateway:
    authServiceUrl: "http://auth-service:8001"
    documentServiceUrl: "http://document-service:8002"
    dietServiceUrl: "http://diet-service:8003"
    healthServiceUrl: "http://health-service:8004"
    notificationServiceUrl: "http://notification-service:8005"
    profileServiceUrl: "http://profile-service:8006"
    adminServiceUrl: "http://admin-service:8007"
  dietService:
    azureOpenaiDeploymentName: "placeholder-openai-deployment-name"
    azureOpenaiApiVersion: "placeholder-openai-api-version"
    azureServiceBusTopicName: "meal-reminders"
  documentService:
    azureStorageContainerName: "nutriai-documents"
  frontend:
    backendUrl: "http://api-gateway:8000"
  notificationService:
    azureServiceBusTopicName: "meal-reminders"
    azureServiceBusSubscriptionName: "email-sender"
    smtpHost: "smtp.gmail.com"
    smtpPort: "587"
    smtpFromEmail: "noreply@nutriai-health.com"
    appUrl: "https://dev.nutriai.example.com"

