namespace: nutriai-prod
keyvaultName: nutriai-kv-prod-v3
clientID: c9c04b34-93e4-4c93-a27c-7c6aa3c88e80
tenantId: cb69c701-1ad6-4282-bcda-0982701e13a6
image:
  registry: nutriaiacrprod.azurecr.io
  pullPolicy: Always
ingress:
  host: nutriai.example.com
admin-service:
  replicas: 1
  image:
    tag: v0.0.5
api-gateway:
  replicas: 2
  image:
    tag: latest
auth-service:
  replicas: 2
  image:
    tag: v0.0.8
diet-service:
  replicas: 2
  image:
    tag: v0.0.4
  hpa:
    minReplicas: 2
    maxReplicas: 5
document-service:
  replicas: 2
  image:
    tag: v0.0.5
frontend:
  replicas: 2
  image:
    tag: v0.0.4
  hpa:
    minReplicas: 2
    maxReplicas: 5
health-service:
  replicas: 2
  image:
    tag: v0.0.7
notification-service:
  replicas: 1
  image:
    tag: v0.0.8
profile-service:
  replicas: 2
  image:
    tag: v0.0.6
api-gateway-service:
  image:
    tag: v0.0.7
config:
  apiGateway:
    authServiceUrl: "http://auth-service:8001"
    documentServiceUrl: "http://document-service:8002"
    dietServiceUrl: "http://diet-service:8003"
    healthServiceUrl: "http://health-service:8004"
    notificationServiceUrl: "http://notification-service:8005"
    profileServiceUrl: "http://profile-service:8006"
    adminServiceUrl: "http://admin-service:8007"
  dietService:
    azureOpenaiDeploymentName: "placeholder-openai-deployment-name"
    azureOpenaiApiVersion: "placeholder-openai-api-version"
    azureServiceBusTopicName: "email-notifications"
  documentService:
    azureStorageContainerName: "nutriai-documents"
  frontend:
    backendUrl: "http://api-gateway:8000"
  notificationService:
    azureServiceBusTopicName: "email-notifications"
    azureServiceBusSubscriptionName: "email-sender"
    smtpHost: "smtp.gmail.com"
    smtpPort: "587"
    smtpFromEmail: "noreply@nutriai-health.com"
    appUrl: "https://nutriai.example.com"
