namespace: nutriai-prod
keyvaultName: nutriai-kv-prod-v3
clientID: c9c04b34-93e4-4c93-a27c-7c6aa3c88e80
tenantId: cb69c701-1ad6-4282-bcda-0982701e13a6
image:
  registry: nutriaiacrprod.azurecr.io
  pullPolicy: Always
ingress:
  host: "nutriai.buzz"
admin-service:
  enabled: true
  replicas: 1
  image:
    tag: v0.0.5
api-gateway:
  enabled: true
  replicas: 2
  image:
    tag: latest
auth-service:
  enabled: true
  replicas: 2
  image:
    tag: v0.1.1
diet-service:
  enabled: true
  replicas: 2
  image:
    tag: v0.0.12
  hpa:
    minReplicas: 2
    maxReplicas: 5
document-service:
  enabled: true
  replicas: 2
  image:
    tag: v0.0.5
frontend:
  enabled: true
  replicas: 2
  image:
    tag: v0.4.0
  hpa:
    minReplicas: 2
    maxReplicas: 5
health-service:
  enabled: true
  replicas: 2
  image:
    tag: v0.0.7
notification-service:
  enabled: true
  replicas: 2
  image:
    tag: v0.0.11
profile-service:
  enabled: true
  replicas: 2
  image:
    tag: v0.0.9
api-gateway-service:
  image:
    tag: v0.0.10
config:
  apiGateway:
    authServiceUrl: "http://auth-service:8001"
    documentServiceUrl: "http://document-service:8002"
    dietServiceUrl: "http://diet-service:8003"
    healthServiceUrl: "http://health-service:8004"
    notificationServiceUrl: "http://notification-service:8005"
    profileServiceUrl: "http://profile-service:8006"
    adminServiceUrl: "http://admin-service:8007"
  dietService:
    azureOpenaiDeploymentName: "gpt-5.1"
    azureOpenaiApiVersion: "2024-02-01"
    azureServiceBusTopicName: "email-notifications"
    azureServiceBusFullyQualifiedNamespace: "nutriai-sb-prod.servicebus.windows.net"
  documentService:
    azureStorageContainerName: "nutriai-documents"
    azureOpenaiDeploymentName: "gpt-5.1"
    azureOpenaiApiVersion: "2024-02-01"
  frontend:
    backendUrl: "http://api-gateway:8000"
  notificationService:
    azureServiceBusTopicName: "email-notifications"
    azureServiceBusSubscriptionName: "email-sender"
    azureServiceBusFullyQualifiedNamespace: "nutriai-sb-prod.servicebus.windows.net"
    smtpHost: "smtp.gmail.com"
    smtpPort: "587"
    smtpFromEmail: "noreply@nutriai-health.com"
    appUrl: "https://nutriai.buzz"
