namespace: nutriai-prod
keyvaultName: nutriai-kv-prod
clientID: prod-identity-client-id
tenantId: placeholder-entra-tenant-id-prod
image:
  registry: nutriaiacr1602.azurecr.io
  pullPolicy: Always
ingress:
  host: nutriai.example.com
admin-service:
  replicas: 1
  image:
    tag: v0.0.2
api-gateway:
  replicas: 2
  image:
    tag: latest
auth-service:
  replicas: 2
  image:
    tag: v0.0.3
diet-service:
  replicas: 2
  image:
    tag: v0.0.2
  hpa:
    minReplicas: 2
    maxReplicas: 5
document-service:
  replicas: 2
  image:
    tag: v0.0.2
frontend:
  replicas: 2
  image:
    tag: v0.0.1
  hpa:
    minReplicas: 2
    maxReplicas: 5
health-service:
  replicas: 2
  image:
    tag: v0.0.2
notification-service:
  replicas: 1
  image:
    tag: v0.0.2
profile-service:
  replicas: 2
  image:
    tag: v0.0.2
api-gateway-service:
  image:
    tag: v0.0.3
